<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ResultBuilder.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="8.0.200" />
    </ItemGroup>

</Project>
